#!/bin/sh

# A pre-push hook for rust codebases that checks formatting, clippy, and tests

set -eu

if [[ "${IGNORE_RUSTHOOKS:=0}" -ne 0 ]]; then
    echo "Ignoring rusthooks"
    exit 0
fi

if ! cargo fmt -- --check
then
    echo "There are some rust code style issues."
    echo "Run `cargo fmt` first."
    exit 1
fi

# Run `ruff` python formatting if it is available
if command -v ruff &> /dev/null && ! ruff format --check .
then
    echo "There are some python code style issues."
    echo "Run `ruff format .` first."
    exit 1
fi

if ! cargo clippy --all-targets --all-features --workspace -- -D warnings
then
    echo "There are some clippy issues."
    exit 1
fi

if ! cargo test --all-features
then
    echo "There are some test issues."
    exit 1
fi

# Run `ruff` python linting if it is available
if command -v ruff &> /dev/null && ! ruff check .
then
    echo "There are some python linting issues."
    exit 1
fi

exit 0
