[tool.poetry]
name = "tket2-py"
version = "0.0.0-alpha.1"
description = "pytket extension for the tket 2 compiler"
classifiers = []                                         # TODO
authors = []                                             # TODO
maintainers = []                                         # TODO
include = ["pyproject.toml"]
license = "Apache-2.0"
readme = "README.md"

packages = [{ include = "tket2-py" }]

[tool.poetry.dependencies]
python = ">=3.10"
pytket = "1.27"

[tool.poetry.group.dev.dependencies]
maturin = "^1.3.0"
pytest = "^8.2.0"
pytest-cov = "^5.0.0"
ruff = "^0.4.4"
mypy = "^1.9.0"
hypothesis = "^6.91.1"
graphviz = "^0.17"
pre-commit = "^3.7.1"

[build-system]
requires = ["maturin~=1.3"]
build-backend = "maturin"

[project]
name = "tket2"
version = "0.0.0-alpha.1"
description = "pytket extension for the tket 2 compiler"
authors = []                                             # TODO
classifiers = []                                         # TODO
requires-python = ">=3.10"
license = { file = "LICENCE" }

[project.urls]
homepage = "https://github.com/CQCL/tket2"
repository = "https://github.com/CQCL/tket2"

[tool.maturin]
manifest-path = "tket2-py/Cargo.toml"
python-source = "tket2-py"
# "extension-module" tells pyo3 we want to build an extension module (skips linking against libpython.so)
features = ["pyo3/extension-module"]

[tool.pytest.ini_options]
# Lark throws deprecation warnings for `src_parse` and `src_constants`.
filterwarnings = "ignore::DeprecationWarning:lark.*"
