[tool.poetry]
name = "tket2-py"
version = "0.1.0a3"
description = "pytket extension for the tket 2 compiler"
classifiers = [
    "Environment :: Console",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
]
authors = ["TKET development team <tket-support@quantinuum.com>"]
maintainers = ["TKET development team <tket-support@quantinuum.com>"]
include = ["pyproject.toml"]
license = "Apache-2.0"
readme = "README.md"

packages = [{ include = "tket2-py" }]

[tool.poetry.dependencies]
python = "^3.10"
# Note: Be sure to update the dependency versions in [project.dependencies] as well
#
# Poetry does not currently follow PEP 621, it will be supported on poetry 2
# https://github.com/python-poetry/poetry/issues/3332
pytket = "1.29.2"
hugr = "^0.4.0"

[tool.poetry.group.dev.dependencies]
maturin = "^1.7.0"
pytest = "^8.2.2"
pytest-cov = "^5.0.0"
ruff = "^0.5.1"
mypy = "^1.10.1"
hypothesis = "^6.105.1"
graphviz = "^0.20"
pre-commit = "^3.7.1"
guppylang = "^0.6.2"

[build-system]
requires = ["maturin~=1.7"]
build-backend = "maturin"

[project]
name = "tket2"
classifiers = [
    "Environment :: Console",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
]
authors = [
    { name = "TKET development team", email = "tket-support@quantinuum.com" },
]
maintainers = [
    { name = "TKET development team", email = "tket-support@quantinuum.com" },
]
version = "0.1.0a3"
description = "pytket extension for the tket 2 compiler"
requires-python = ">=3.10"
license = { file = "LICENCE" }

# Note: Be sure to update the dependency versions in [tool.poetry.dependencies] as well
dependencies = ['pytket >= 1.29.2, < 2', 'hugr >= 0.4.0, < 0.5']

[project.urls]
homepage = "https://github.com/CQCL/tket2"
repository = "https://github.com/CQCL/tket2"

[tool.maturin]
module-name = "tket2._tket2"
manifest-path = "tket2-py/Cargo.toml"
python-source = "tket2-py"
# "extension-module" tells pyo3 we want to build an extension module (skips linking against libpython.so)
features = ["pyo3/extension-module"]

[tool.pytest]
pythonpath = "tket2-py"

[tool.pytest.ini_options]
# Lark throws deprecation warnings for `src_parse` and `src_constants`.
filterwarnings = "ignore::DeprecationWarning:lark.*"

[tool.pyright]
# Rust bindings have typing stubs but no python source code.
reportMissingModuleSource = "none"

[[tool.mypy.overrides]]
# Ignore errors in tikv-jemalloc.
module = "gen_run_tests.*"
ignore_errors = true
