[tool.uv.workspace]
members = ["tket-py", "tket-eccs", "tket-exts", "qis-compiler"]

[dependency-groups]
dev = [
    "maturin >=1.7.0,<2",
    "pytest >=8.3.2,<9",
    "pytest-cov ~=7.0",
    "pytest-snapshot~=0.9.0",
    "ruff >=0.6.2,<0.7",
    "mypy >=1.17.1,<2",
    "hypothesis >=6.111.1,<7",
    "graphviz ~=0.20.0",
    "pre-commit ~=4.3",
    "conan >= 2.0.0,<3",
    # Required to run `maturin develop`
    "pip >=25",
    # Pyyaml 0.6.0 makes setuptools fail. This ensures we're using a newer version.
    "pyyaml >=6.0.2",
    "cibuildwheel>=2.23.2",
    "pytket~=2.9.1",
    "guppylang~=0.21.0",
]

[tool.uv]
prerelease = "explicit"

[tool.mypy]
exclude = '''(?x)(
    ^target/        # Build artifacts
    | ^notebooks/   # Examples
    | ^test_files/  # Test files
    | ^tket1-passes/tket-c-api/ # Do not check conan files
)'''
ignore_missing_imports = true

# TODO: Fix the lint errors and enable this
#strict = true

[tool.coverage.report]
exclude_also = [
    # Don't complain about missing coverage on typing imports
    "if TYPE_CHECKING:",

    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",
    "raise InternalGuppyError",

    # Don't complain about abstract methods, they aren't run:
    "@abstractmethod",
]
