# Automatic changelog generation for rust projects

[workspace]
# Open the release PR as a draft
pr_draft = true

# Default to not processing the packages
release = false

# Enforce adding the project name in the git tag, to avoid collisions with python.
# (This would normally only be enabled once there are multiple packages in the workspace)
git_tag_name = "{{ package }}-v{{ version }}"
git_release_name = "{{ package }}: v{{ version }}"

[changelog]
sort_commits = "oldest"

commit_parsers = [
    { message = "^feat", group = "New Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^docs", group = "Documentation" },
    { message = "^style", group = "Styling" },
    { message = "^refactor", group = "Refactor" },
    { message = "^perf", group = "Performance" },
    { message = "^test", group = "Testing" },
    { message = "^chore", group = "Miscellaneous Tasks", skip = true },
    { message = "^revert", group = "Reverted changes", skip = true },
    { message = "^ci", group = "CI", skip = true },
]

[[package]]
name = "tket2"
release = true

# Temporarily disabled until the first manual release
publish = false
