[package]
name = "pyrs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyrs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "^0.16.5", features = ["extension-module"] }
tket2 = { path = "../", features = ["pyo3"] }
portgraph = { path = "../ext/portgraph", features = ["pyo3"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tket-json-rs = { git = "https://github.com/CQCL/tket-json-rs", features = ["pyo3"] }
quantinuum-hugr = { version = "0.1.0", git="https://github.com/CQCL-DEV/hugr", branch="opaque-new" }