# List the available commands
help:
    @just --list --justfile {{justfile()}}

# Re-generate all hugr files and their mermaid diagrams.
regenerate: regenerate-hugrs

# Re-generate all hugr files.
regenerate-hugrs:
    #!/usr/bin/env sh
    # Find all examples in subdirectories and re-run them.
    for example in $(find resources -type f -name "*.py"); do
        echo "Re-generating $example"
        uv run --no-project "$example"
    done
