//! Tests optimizing Guppy-generated programs.

use std::fs;
use std::io::BufReader;
use std::path::Path;

use hugr::algorithms::merge_bbs::merge_basic_blocks;
use hugr::hugr::hugrmut::HugrMut;
use hugr::hugr::views::RootCheckable;
use hugr::ops::OpTag;
use hugr::ops::OpTrait;
use hugr::{Hugr, HugrView};
use itertools::Itertools;
use rstest::{fixture, rstest};
use tket::passes::find_tuple_unpack_rewrites;
use tket::Circuit;
use tket_qsystem::QSystemPass;

const GUPPY_EXAMPLES_DIR: &str = "../test_files/guppy_optimization";

fn load_guppy_circuit(name: &str) -> Hugr {
    let file = Path::new(GUPPY_EXAMPLES_DIR).join(format!("{name}/{name}.hugr"));
    let reader = fs::File::open(file).unwrap();
    let reader = BufReader::new(reader);
    Hugr::load(reader, None).unwrap()
}

#[fixture]
fn guppy_angles() -> Hugr {
    load_guppy_circuit("angles")
}

#[fixture]
fn guppy_false_branch() -> Hugr {
    load_guppy_circuit("false_branch")
}

#[fixture]
fn guppy_nested() -> Hugr {
    load_guppy_circuit("nested")
}

#[fixture]
fn guppy_ranges() -> Hugr {
    load_guppy_circuit("ranges")
}

#[fixture]
fn guppy_simple_cx() -> Hugr {
    load_guppy_circuit("simple_cx")
}

/// Run some simple optimization passes on the guppy-generated HUGRs and validate the result.
#[rstest]
#[case::angles(guppy_angles())]
#[case::false_branch(guppy_false_branch())]
#[case::nested(guppy_nested())]
#[case::ranges(guppy_ranges())]
#[case::simple_cx(guppy_simple_cx())]
fn optimise_guppy(#[case] mut hugr: Hugr) {
    let cfgs = hugr
        .entry_descendants()
        .filter(|&n| hugr.get_optype(n).is_cfg())
        .collect_vec();
    for cfg in cfgs {
        let mut rerooted = hugr.with_entrypoint_mut(cfg);
        let cfg = (&mut rerooted).try_into_checked().unwrap();
        merge_basic_blocks(cfg);
    }

    // Remove sequences of tuple pack-unpack operations,
    // typically generated by guppy.
    let dfg_blocks = hugr
        .entry_descendants()
        .filter(|&n| hugr.get_optype(n).tag() < OpTag::DataflowParent)
        .collect_vec();
    for dfg_block in dfg_blocks {
        println!("Removing tuple unpacks from DFG block {dfg_block}");
        let mut circuit = Circuit::new(hugr.with_entrypoint_mut(dfg_block));
        let rewrites = find_tuple_unpack_rewrites(&circuit).collect_vec();
        for rewrite in rewrites {
            rewrite.apply(&mut circuit).unwrap();
        }
    }

    QSystemPass::default()
        // TODO: Enabling constant fold causes a validation error.
        //.with_constant_fold(true)
        .run(&mut hugr)
        .unwrap();

    hugr.validate().unwrap_or_else(|e| panic!("{e}"));

    // TODO: Once the required optimisations are implemented, we should be able to check that the circuits are fully optimized.
    // (Most example circuits optimize to identity functions).
}
