"""`tket-eccs` is a Python package containing compiler rewrite sets used for `tket`'s optimisation passes.

This package is intended to be used as an internal dependency for `tket`.
"""

# This is updated by our release-please workflow, triggered by this
# annotation: x-release-please-version
__version__ = "0.5.1"

from importlib import resources
from pathlib import Path


def nam_6_3() -> Path:
    """Get the path to the included `nam_6_3.rwr` rewriter.

    This is a rewrite set obtained from the equivalence classes of circuits with
    up to 3 qubits and 6 gates on the Nam gateset, as
    generated by TASO.

    See https://dl.acm.org/doi/10.1145/3341301.3359630
    """
    with resources.as_file(
        resources.files("tket_eccs").joinpath("data/nam_6_3.rwr")
    ) as r:
        rewriter = Path(r)
    return rewriter


def clifford_t_6_3() -> Path:
    """Get the path to the included `clifford_t_6_3.rwr` rewriter.

    This is a rewrite set obtained from the equivalence classes of circuits with
    up to 3 qubits and 6 gates on the T, X, H, S and CX gateset, as
    generated by TASO.
    """
    with resources.as_file(
        resources.files("tket_eccs").joinpath("data/clifford_t_6_3.rwr")
    ) as r:
        rewriter = Path(r)
    return rewriter
