name: "Install tket-c-api C++ library"
description: "Retrieve cached tket-c-api C++ library or build if needed"

inputs:
  install-path:
    description: "Path where the tket-c-api library will be installed"
    required: true

runs:
  using: composite
  steps:
    - name: Attempt to retrieve cached tket-c-api
      uses: actions/cache/restore@v4
      id: cache
      with:
        path: ${{ inputs.install-path }}
        key: ${{ runner.os }}-${{ hashFiles('tket1-passes/**') }}-${{ hashFiles('.github/actions/tket-c-api/action.yml') }}

    - name: Install conan
      if: steps.cache.outputs.cache-hit != 'true'
      uses: conan-io/setup-conan@v1
      with:
        cache_packages: true

    - name: Set up conan remote
      if: steps.cache.outputs.cache-hit != 'true' && runner.os != 'Windows'
      shell: bash
      run: |
        conan remote add tket-libs https://quantinuumsw.jfrog.io/artifactory/api/conan/tket1-libs --index 0

    - name: Set up conan remote (Windows)
      if: steps.cache.outputs.cache-hit != 'true' && runner.os == 'Windows'
      shell: pwsh
      run: |
        conan remote add tket-libs https://quantinuumsw.jfrog.io/artifactory/api/conan/tket1-libs --index 0

    - name: Build and install tket-c-api
      if: steps.cache.outputs.cache-hit != 'true' && runner.os != 'Windows'
      shell: bash
      run: |
        cd tket1-passes
        mkdir -p ${{ inputs.install-path }}
        CONAN_OUTPUT=$(conan install . --build=missing --options="tket-c-api/*:shared=True" --format=json)
        CONAN_LIB_FOLDER=$(echo "$CONAN_OUTPUT" | jq -r ".graph.nodes.\"1\".package_folder")
        cp -r "$CONAN_LIB_FOLDER/p" "${{ inputs.install-path }}"

    - name: Build and install tket-c-api (Windows)
      if: steps.cache.outputs.cache-hit != 'true' && runner.os == 'Windows'
      shell: pwsh
      run: |
        Set-Location tket1-passes
        New-Item -ItemType Directory -Force -Path "${{ inputs.install-path }}" | Out-Null
        $conanOutput = conan install . --build=missing --options="tket-c-api/*:shared=True" --format=json
        $conanJson = $conanOutput | ConvertFrom-Json
        $conanLibFolder = $conanJson.graph.nodes.'1'.package_folder
        $sourceRoot = Join-Path $conanLibFolder 'p'
        # Copy files while translating any embedded forward slashes to Windows directories
        # This is a workaround for conan installing files with forward slashes on Windows.
        Get-ChildItem -LiteralPath $sourceRoot -Recurse -Force | ForEach-Object {
          if ($_.PSIsContainer) { return }
          $relative = $_.FullName.Substring($sourceRoot.Length).TrimStart('\\','/')
          $relativeWin = $relative -replace '/', '\\'
          $destPath = Join-Path "${{ inputs.install-path }}" $relativeWin
          $destDir = Split-Path -Parent $destPath
          New-Item -ItemType Directory -Force -Path $destDir | Out-Null
          Copy-Item -LiteralPath $_.FullName -Destination $destPath -Force
        }

    - name: Upload compiled library to cache
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ inputs.install-path }}
        key: ${{ steps.cache.outputs.cache-primary-key }}

    - name: List library files
      shell: bash
      run: |
        echo "tket-c-api library files:"
        ls -lR "${{ inputs.install-path }}"
