name: "Install tket-c-api C++ library"
description: "Retrieve cached tket-c-api C++ library or build if needed."

inputs:
  install-path:
    description: "Path where the tket-c-api library will be installed"
    required: true
  target:
    description: "Target platform"
    required: false
    default: ${{ runner.arch }}
  compatibility:
    description: "Generic compatibility, e.g. 'manylinux_2_28' on linux or '11.0' on macos."
    required: false
    default: 'N/A'
runs:
  using: composite
  steps:
    - name: Attempt to retrieve cached tket-c-api
      uses: actions/cache@v4
      id: cache
      with:
        path: ${{ inputs.install-path }}
        key: ${{ runner.os }}-${{ inputs.target }}-${{ hashFiles('tket1-passes/conanfile.txt') }}-${{ hashFiles('tket1-passes/scripts/build.sh') }}-${{ hashFiles('tket1-passes/scripts/build/${{ inputs.target }}.sh') }}-${{ hashFiles('.github/actions/tket-c-api/action.yml') }}

    - name: Run install script
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        tket1-passes/scripts/build.sh \
          "${{ inputs.target }}" \
          "${{ inputs.compatibility }}" \
          "${{ inputs.install-path }}"

    - name: List tket-c-api library files
      shell: bash
      run: |
        echo "tket-c-api library files:"
        find "${{ inputs.install-path }}" -type f
