name: "Install tket-c-api C++ library"
description: "Retrieve cached tket-c-api C++ library or build if needed"

inputs:
  install-path:
    description: "Path where the tket-c-api library will be installed"
    required: true
  target:
    description: "Target platform, used for caching"
    required: false
    default: ${{ runner.arch }}
runs:
  using: composite
  steps:
    - name: Attempt to retrieve cached tket-c-api
      uses: actions/cache/restore@v4
      id: cache
      with:
        path: ${{ inputs.install-path }}
        key: ${{ runner.os }}-${{ inputs.target }}-${{ hashFiles('tket1-passes/conanfile.txt') }}-${{ hashFiles('tket1-passes/conan-profiles/**') }}-${{ hashFiles('.github/actions/tket-c-api/action.yml') }}

    - name: Install conan
      if: steps.cache.outputs.cache-hit != 'true'
      uses: conan-io/setup-conan@v1
      with:
        cache_packages: true

    - name: Set up conan remote
      if: steps.cache.outputs.cache-hit != 'true' && runner.os != 'Windows'
      shell: bash
      run: |
        conan remote add tket-libs https://quantinuumsw.jfrog.io/artifactory/api/conan/tket1-libs --index 0

    - name: Set up conan remote (Windows)
      if: steps.cache.outputs.cache-hit != 'true' && runner.os == 'Windows'
      shell: pwsh
      run: |
        conan remote add tket-libs https://quantinuumsw.jfrog.io/artifactory/api/conan/tket1-libs --index 0

    - name: Build and install tket-c-api
      if: steps.cache.outputs.cache-hit != 'true' && runner.os != 'Windows'
      shell: bash
      run: |
        cd tket1-passes
        mkdir -p ${{ inputs.install-path }}
        CONAN_OUTPUT=$(conan install . --build=missing --options="tket-c-api/*:shared=True" --format=json)
        CONAN_LIB_FOLDER=$(echo "$CONAN_OUTPUT" | jq -r ".graph.nodes.\"1\".package_folder")
        echo "CONAN_LIB_FOLDER: $CONAN_LIB_FOLDER"
        cp -r "$CONAN_LIB_FOLDER" "${{ inputs.install-path }}"

    - name: Build and install tket-c-api (Windows)
      if: steps.cache.outputs.cache-hit != 'true' && runner.os == 'Windows'
      shell: pwsh
      run: |
        Set-Location tket1-passes
        New-Item -ItemType Directory -Force -Path "${{ inputs.install-path }}" | Out-Null
        $conanOutput = conan install . --build=missing --options="tket-c-api/*:shared=True" --format=json
        $conanJson = $conanOutput | ConvertFrom-Json
        $conanLibFolder = $conanJson.graph.nodes.'1'.package_folder
        echo "CONAN_LIB_FOLDER: $conanLibFolder"
        Copy-Item -Recurse -Force -Path "$conanLibFolder" -Destination "${{ inputs.install-path }}"

    - name: Upload compiled library to cache
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ inputs.install-path }}
        key: ${{ steps.cache.outputs.cache-primary-key }}

    - name: List library files
      shell: bash
      run: |
        echo "tket-c-api library files:"
        ls -lR "${{ inputs.install-path }}"
