name: "Install tket-c-api C++ library"
description: "Retrieve cached tket-c-api C++ library or build if needed"

inputs:
  install-path:
    description: "Path where the tket-c-api library will be installed"
    required: true
  target:
    description: "Target platform, used for caching"
    required: false
    default: ${{ runner.arch }}
runs:
  using: composite
  steps:
    - name: Attempt to retrieve cached tket-c-api
      uses: actions/cache/restore@v4
      id: cache
      with:
        path: ${{ inputs.install-path }}
        key: ${{ runner.os }}-${{ inputs.target }}-${{ hashFiles('tket1-passes/conanfile.txt') }}-${{ hashFiles('tket1-passes/conan-profiles/**') }}-${{ hashFiles('.github/actions/tket-c-api/action.yml') }}

    - name: Install conan
      if: steps.cache.outputs.cache-hit != 'true'
      uses: conan-io/setup-conan@v1
      with:
        cache_packages: true

    - name: Set up conan remote
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        conan remote add tket-libs https://quantinuumsw.jfrog.io/artifactory/api/conan/tket1-libs --index 0

    - name: Install cross-compilation toolchains
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        TARGET="${{ inputs.target }}"

        # Install cross-compilation toolchains based on target
        case "$TARGET" in
          aarch64-unknown-linux-gnu|aarch64-unknown-linux-musl)
            sudo apt-get update
            sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
            ;;
          armv7-unknown-linux-gnueabihf|armv7-unknown-linux-musleabihf)
            sudo apt-get update
            sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
            ;;
          i686-unknown-linux-gnu|i686-unknown-linux-musl)
            sudo apt-get update
            sudo apt-get install -y gcc-multilib g++-multilib
            ;;
          x86_64-unknown-linux-gnu|x86_64-unknown-linux-musl)
            # Native compilation, no cross-compiler needed
            ;;
          *)
            # For other targets, check if cross-compilation is needed
            if [[ "$TARGET" == *"linux"* ]] && [[ "$TARGET" != *"x86_64"* ]]; then
              echo "Warning: Unknown Linux target $TARGET, cross-compilation may fail"
            fi
            ;;
        esac

    - name: Determine conan profile
      if: steps.cache.outputs.cache-hit != 'true'
      id: conan-profile
      shell: bash
      run: |
        TARGET="${{ inputs.target }}"
        PROFILE=""

        case "$TARGET" in
          aarch64-unknown-linux-gnu)
            PROFILE="linux-aarch64-gcc14"
            ;;
          aarch64-unknown-linux-musl)
            PROFILE="linux-aarch64-musl-gcc14"
            ;;
          armv7-unknown-linux-gnueabihf)
            PROFILE="linux-armv7-gcc14"
            ;;
          armv7-unknown-linux-musleabihf)
            PROFILE="linux-armv7-musl-gcc14"
            ;;
          i686-unknown-linux-gnu)
            PROFILE="linux-i686-gcc14"
            ;;
          i686-unknown-linux-musl)
            PROFILE="linux-i686-musl-gcc14"
            ;;
          x86_64-unknown-linux-gnu)
            PROFILE="linux-x86_64-gcc14"
            ;;
          x86_64-unknown-linux-musl)
            PROFILE="linux-x86_64-musl-gcc14"
            ;;
          x86_64-pc-windows-msvc)
            PROFILE="windows-2025"
            ;;
          *)
            # For non-Linux targets or if no match, let conan generate a default profile
            if [[ "$TARGET" == *"apple"* ]] && [[ "$TARGET" == *"aarch64"* ]]; then
              PROFILE="macos-15"
            elif [[ "$TARGET" == *"apple"* ]] && [[ "$TARGET" == *"x86_64"* ]]; then
              PROFILE="macos-15-intel"
            elif [[ "$TARGET" == *"windows"* ]] && [[ "$TARGET" == *"msvc"* ]]; then
              PROFILE="windows-2025"
            elif [[ "$TARGET" == *"armv8"* ]] || [[ "$TARGET" == *"aarch64"* ]]; then
              PROFILE="linux-armv8-gcc14"
            elif [[ "$TARGET" == *"x86_64"* ]]; then
              PROFILE="linux-x86_64-gcc14"
            else
              PROFILE=""
            fi
            ;;
        esac

        if [ -z "$PROFILE" ]; then
          echo "No profile found for target: $TARGET, using default"
          echo "profile=" >> $GITHUB_OUTPUT
          echo "use_profile=false" >> $GITHUB_OUTPUT
        else
          # Check if profile exists in tket1-passes/conan-profiles directory
          if [ -f "tket1-passes/conan-profiles/$PROFILE" ]; then
            PROFILE_PATH="tket1-passes/conan-profiles/$PROFILE"
            echo "profile=$PROFILE_PATH" >> $GITHUB_OUTPUT
            echo "use_profile=true" >> $GITHUB_OUTPUT
            echo "Selected profile: $PROFILE_PATH"
          else
            echo "Profile $PROFILE not found in tket1-passes/conan-profiles/, using default"
            echo "profile=" >> $GITHUB_OUTPUT
            echo "use_profile=false" >> $GITHUB_OUTPUT
          fi
        fi

    - name: Build and install tket-c-api
      if: steps.cache.outputs.cache-hit != 'true' && runner.os != 'Windows'
      shell: bash
      run: |
        cd tket1-passes
        mkdir -p ${{ inputs.install-path }}

        # Set up cross-compilation environment variables if needed
        TARGET="${{ inputs.target }}"
        export CC=""
        export CXX=""

        case "$TARGET" in
          aarch64-unknown-linux-gnu|aarch64-unknown-linux-musl)
            export CC="aarch64-linux-gnu-gcc"
            export CXX="aarch64-linux-gnu-g++"
            ;;
          armv7-unknown-linux-gnueabihf|armv7-unknown-linux-musleabihf)
            export CC="arm-linux-gnueabihf-gcc"
            export CXX="arm-linux-gnueabihf-g++"
            ;;
          i686-unknown-linux-gnu|i686-unknown-linux-musl)
            # For i686, conan profile with arch=x86 should handle -m32 automatically
            # No need to set CC/CXX explicitly
            ;;
        esac

        if [ -n "$CC" ]; then
          echo "Using cross-compiler: CC=$CC, CXX=$CXX"
          # Verify cross-compiler is available and working
          $CC --version || echo "Warning: Failed to get $CC version"
        fi

        # Build conan install command
        CONAN_CMD="conan install . --build=missing --options=\"tket-c-api/*:shared=True\""

        if [ "${{ steps.conan-profile.outputs.use_profile }}" == "true" ]; then
          CONAN_CMD="$CONAN_CMD --profile=${{ github.workspace }}/${{ steps.conan-profile.outputs.profile }}"
          echo "Using profile: ${{ steps.conan-profile.outputs.profile }}"
        else
          echo "Using default conan profile"
        fi

        CONAN_CMD="$CONAN_CMD --format=json"
        echo "Running: $CONAN_CMD"

        CONAN_OUTPUT=$(eval $CONAN_CMD)
        CONAN_LIB_FOLDER=$(echo "$CONAN_OUTPUT" | jq -r ".graph.nodes.\"1\".package_folder")
        echo "CONAN_LIB_FOLDER: $CONAN_LIB_FOLDER"
        cp -r "$CONAN_LIB_FOLDER/"* "${{ inputs.install-path }}/"

    - name: Build and install tket-c-api (Windows)
      if: steps.cache.outputs.cache-hit != 'true' && runner.os == 'Windows'
      shell: pwsh
      run: |
        Set-Location tket1-passes
        New-Item -ItemType Directory -Force -Path "${{ inputs.install-path }}" | Out-Null

        # Verify conan is available
        # The conan-io/setup-conan action should have installed it, but verify
        if (-not (Get-Command conan -ErrorAction SilentlyContinue)) {
          Write-Error "conan not found in PATH"
          Write-Output "PATH: $env:PATH"
          Write-Output "Python location: $(Get-Command python -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Source)"
          Write-Output "Python Scripts: $env:LOCALAPPDATA\Programs\Python\Python*\Scripts"
        } else {
          $conanPath = (Get-Command conan).Source
          Write-Output "conan found: $conanPath"
          conan --version
        }

        # Build conan install command
        $conanArgs = @("install", ".", "--build=missing", "--options=tket-c-api/*:shared=True")

        if ("${{ steps.conan-profile.outputs.use_profile }}" -eq "true") {
          $profilePath = "${{ github.workspace }}/${{ steps.conan-profile.outputs.profile }}"
          $conanArgs += "--profile=$profilePath"
          Write-Output "Using profile: ${{ steps.conan-profile.outputs.profile }}"
        } else {
          Write-Output "Using default conan profile"
        }

        $conanArgs += "--format=json"
        $conanCmdStr = "conan " + ($conanArgs -join " ")
        Write-Output "Running: $conanCmdStr"

        $conanOutput = & conan $conanArgs
        $conanJson = $conanOutput | ConvertFrom-Json
        $conanLibFolder = $conanJson.graph.nodes.'1'.package_folder
        Write-Output "CONAN_LIB_FOLDER: $conanLibFolder"
        Copy-Item -Recurse -Force -Path "$conanLibFolder\*" -Destination "${{ inputs.install-path }}"

    - name: Upload compiled library to cache
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ inputs.install-path }}
        key: ${{ steps.cache.outputs.cache-primary-key }}

    - name: List tket-c-api library files
      shell: bash
      run: |
        echo "tket-c-api library files:"
        find "${{ inputs.install-path }}" -type f
