[package]
name = "bench-vs-quartz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.2"
lazy_static = "1.4.0"
quantinuum-hugr = { workspace = true }
serde = { version = "1.0.188", features = ["derive"] }
tket2 = { path = "../", features = ["portmatching"] }
