[package]
name = "compile-rewriter"
edition = { workspace = true }
version = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
license-file = { workspace = true }

[dependencies]
clap = { workspace = true, features = ["derive"] }
tket2 = { workspace = true, features = ["portmatching"] }
hugr = { workspace = true }
itertools = { workspace = true }
