[package]
name = "compile-matcher"
edition = { workspace = true }
version = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
license-file = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
tket2 = { workspace = true, features = ["portmatching"] }
quantinuum-hugr = { workspace = true }
itertools = { workspace = true }
