name: Unsoundness checks

on:
  schedule:
    # Weekly on Monday at 04:00 UTC
    - cron: '0 4 * * 1'
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "--cfg=ci_run"
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  # Permissive provenance is required due to warnings in bitvec 1.0.1
  # Proptest flags required to fix https://github.com/proptest-rs/proptest/issues/253
  MIRIFLAGS: '-Zmiri-permissive-provenance -Zmiri-env-forward=PROPTEST_DISABLE_FAILURE_PERSISTENCE'
  PROPTEST_DISABLE_FAILURE_PERSISTENCE: true

jobs:

  miri:
    name: "Miri"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
      - uses: mozilla-actions/sccache-action@v0.0.9
      - name: Test with Miri
        run: cargo miri test

  create-issue:
    uses: CQCL/hugrverse-actions/.github/workflows/create-issue.yml@main
    needs: miri
    if: always() && needs.miri.result == 'failure' && github.ref == 'refs/heads/main'
    secrets:
        GITHUB_PAT: ${{ secrets.HUGRBOT_PAT }}
    with:
        title: "💥 Unsoundness check fail on main"
        body: |
            The unsoundness check for `CQCL/tket2` failed.

            [Please investigate](https://github.com/CQCL/tket2/actions/runs/${{ github.run_id }}).
        unique-label: "unsoundness-checks"
        other-labels: "bug"
