name: Run tests with TKET1 bindings

on:
  #push:
  #  branches:
  #    - main 
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "--cfg=ci_run"
  CONAN_PROFILE: "./.github/conan_profile"

jobs:
  benches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Setup Conan
        uses: ./.github/actions/setup-conan
        with:
          conan-profile: ${{ env.CONAN_PROFILE }}
          gcc-version: 11
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v0-conan
      - name: Build benchmarks with all features
        run: cargo bench --verbose --no-run --all-features

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          #- rust: 1.70.0  # Update once MSRV != stable
          - rust: stable
            cache: true
          - rust: beta
            cache: true
          - rust: nightly
            cache: true

    steps:
      - uses: actions/checkout@v3
      - id: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Configure default rust toolchain
        run: rustup override set ${{steps.toolchain.outputs.name}}
      - name: Setup Conan
        uses: ./.github/actions/setup-conan
        with:
          conan-profile: ./.github/conan_profile
          gcc-version: 11
      - uses: Swatinem/rust-cache@v2
        if: ${{ matrix.cache }}
        with:
          prefix-key: v0-rust-${{ matrix.rust }}-conan
      - name: Build with all features
        run: cargo build --verbose --all-features
      - name: Tests with all features
        run: cargo test --verbose --all-features